// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetViTeca.Data;

#nullable disable

namespace NetViTeca.Data.Migrations
{
    [DbContext(typeof(NetViTecaDbContext))]
    partial class NetViTecaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NetViTeca.Core.Models.Biblioteca", b =>
                {
                    b.Property<int>("idLibro")
                        .HasColumnType("int");

                    b.Property<int?>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("idLibro", "idUsuario");

                    b.HasIndex("idUsuario");

                    b.ToTable("Biblioteca", (string)null);
                });

            modelBuilder.Entity("NetViTeca.Core.Models.Genero", b =>
                {
                    b.Property<int?>("idGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("idGenero"));

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("idGenero");

                    b.HasIndex("genero")
                        .IsUnique()
                        .HasDatabaseName("IX_Genero_genero");

                    b.ToTable("Genero", (string)null);
                });

            modelBuilder.Entity("NetViTeca.Core.Models.Libro", b =>
                {
                    b.Property<int>("idLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idLibro"));

                    b.Property<string>("autor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("cantidadPaginas")
                        .HasColumnType("int");

                    b.Property<string>("editorial")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("idGenero")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("idLibro");

                    b.HasIndex("idGenero");

                    b.HasIndex("titulo")
                        .IsUnique()
                        .HasDatabaseName("IX_Libro_Titulo");

                    b.ToTable("Libro", (string)null);
                });

            modelBuilder.Entity("NetViTeca.Core.Models.Usuario", b =>
                {
                    b.Property<int?>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("idUsuario"));

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("numeroTelefono")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("idUsuario");

                    b.HasIndex("nombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuario_NombreUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("NetViTeca.Core.Models.Biblioteca", b =>
                {
                    b.HasOne("NetViTeca.Core.Models.Libro", "Libros")
                        .WithMany()
                        .HasForeignKey("idLibro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetViTeca.Core.Models.Usuario", "Usuarios")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("NetViTeca.Core.Models.Libro", b =>
                {
                    b.HasOne("NetViTeca.Core.Models.Genero", "genero")
                        .WithMany("libros")
                        .HasForeignKey("idGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("genero");
                });

            modelBuilder.Entity("NetViTeca.Core.Models.Genero", b =>
                {
                    b.Navigation("libros");
                });
#pragma warning restore 612, 618
        }
    }
}
